name: viskex CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  test:
    if: >-
      (
        (
          github.event_name == 'schedule'
          && github.repository == 'viskex/viskex'
        ) || (
            github.event_name != 'schedule'
            && !(
              contains(github.event.head_commit.message, '[ci skip]')
              || contains(github.event.head_commit.message, '[skip ci]')
            )
        )
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - backend: dolfinx
            container: dolfinx/dolfinx:nightly
            setup_container: |
              export DEBIAN_FRONTEND="noninteractive"
              apt -y -qq update
              apt install -y -qq libgl1-mesa-glx xvfb
              rm /usr/local/lib/python3.10/dist-packages/petsc4py/py.typed
          - backend: firedrake
            container: firedrakeproject/firedrake
            setup_container: |
              export DEBIAN_FRONTEND="noninteractive"
              apt -y -qq update
              apt install -y -qq libgl1-mesa-glx xvfb
              rm /home/firedrake/firedrake/lib/python3.10/site-packages/petsc4py/py.typed
              echo "/home/firedrake/firedrake/bin" >> $GITHUB_PATH
      fail-fast: false
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Setup container
        run: ${{ matrix.setup_container }}
      - name: Determine which steps to skip
        id: skips
        run: |
          echo "run_unit_tests=false" >> $GITHUB_OUTPUT
          echo "run_coverage=false" >> $GITHUB_OUTPUT
      - name: Install viskex
        run: python3 -m pip install .[docs,lint,tests,tutorials]
      - name: Update flake8 and mypy configuration
        run: |
          if [[ "${{ matrix.backend }}" == "dolfinx" ]]; then
            sed -i 's@from viskex.firedrake_plotter import FiredrakePlotter as firedrake@# line removed by CI@g' viskex/__init__.py
            sed -i 's@exclude = .eggs, build, dist@exclude = .eggs, build, dist, viskex/firedrake_plotter.py@g' setup.cfg
            sed -i 's@exclude = (^\\\.eggs|^build|^dist|conftest\\\.py\$)@exclude = (^\\\.eggs|^build|^dist|conftest\\\.py\$|^viskex/firedrake_plotter\\\.py\$)@g' setup.cfg
            echo "[tool.nbqa.exclude]" >> pyproject.toml
            echo 'flake8 = "^tutorials/.*/tutorial_.*_firedrake"' >> pyproject.toml
            echo 'mypy = "^tutorials/.*/tutorial_.*_firedrake"' >> pyproject.toml
          elif [[ "${{ matrix.backend }}" == "firedrake" ]]; then
            sed -i 's@from viskex.dolfinx_plotter import DolfinxPlotter as dolfinx@# line removed by CI@g' viskex/__init__.py
            echo "[mypy-dolfinx]" >> setup.cfg
            echo "ignore_missing_imports = True" >> setup.cfg
            echo "[mypy-dolfinx.*]" >> setup.cfg
            echo "ignore_missing_imports = True" >> setup.cfg
            sed -i 's@exclude = .eggs, build, dist@exclude = .eggs, build, dist, viskex/dolfinx_plotter.py@g' setup.cfg
            sed -i 's@exclude = (^\\\.eggs|^build|^dist|conftest\\\.py\$)@exclude = (^\\\.eggs|^build|^dist|conftest\\\.py\$|^viskex/dolfinx_plotter\\\.py\$)@g' setup.cfg
            echo "[tool.nbqa.exclude]" >> pyproject.toml
            echo 'flake8 = "^tutorials/.*/tutorial_.*_dolfinx"' >> pyproject.toml
            echo 'mypy = "^tutorials/.*/tutorial_.*_dolfinx"' >> pyproject.toml
          else
            echo "Invalid backend"
            exit 1
          fi
        shell: bash
      - name: Run flake8 and mypy checks on python files
        run: |
          python3 -m flake8 .
          python3 -m mypy .
      - name: Run documentation generation
        run: |
          cd docs && make html
      - name: Run unit tests
        if: steps.skips.outputs.run_unit_tests != 'false'
        run: |
          for VISKEX_PYVISTA_BACKEND in "client" "server" "panel" "static"; do
            echo "Testing ${VISKEX_PYVISTA_BACKEND} pyvista backend"
            COVERAGE_FILE=.coverage_unit_${{ matrix.backend }}_${VISKEX_PYVISTA_BACKEND} VISKEX_PYVISTA_BACKEND=${VISKEX_PYVISTA_BACKEND} python3 -m pytest --cov=viskex --cov-report= tests/unit
          done
      - name: Run flake8 and mypy checks on tutorial files
        run: |
          NO_TESTS_COLLECTED=5
          python3 -m pytest --ipynb-action=create-notebooks tutorials || (($?==$NO_TESTS_COLLECTED))
          python3 -m nbqa flake8 .
          python3 -m nbqa mypy .
        shell: bash
      - name: Check for stray outputs, counts and metadata in ipynb files
        uses: RBniCS/check-jupyter-metadata-action@main
        with:
          pattern: "tutorials/**/*.ipynb"
      - name: Run tutorials
        run: |
          export DISPLAY=":99"
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          for VISKEX_PYVISTA_BACKEND in "client" "server" "panel" "static"; do
            echo "Testing ${VISKEX_PYVISTA_BACKEND} pyvista backend"
            COVERAGE_FILE=.coverage_tutorials_${{ matrix.backend }} VISKEX_PYVISTA_BACKEND=${VISKEX_PYVISTA_BACKEND} python3 -m pytest --cov=viskex --cov-report= tutorials
          done
      - name: Store coverage reports as artifact
        if: steps.skips.outputs.run_coverage != 'false'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.backend }}
          path: |
            .coverage_unit_${{ matrix.backend }}
            .coverage_tutorials_${{ matrix.backend }}
          retention-days: 1
      - name: Upload tutorials logs as an artifact in case of failure
        if: failure() || cancelled()
        uses: actions/upload-artifact@v3
        with:
          name: "tutorials-logs-${{ matrix.backend }}"
          path: |
            tutorials/**/.ipynb_pytest/**/*.log*
    outputs:
      run_unit_tests: ${{ steps.skips.outputs.run_unit_tests }}
      run_coverage: ${{ steps.skips.outputs.run_unit_tests }}

  combine_coverage:
    runs-on: ubuntu-latest
    container: ubuntu
    needs: [test]
    if: needs.test.outputs.run_coverage != 'false'
    steps:
      - uses: actions/checkout@v3
      - name: Setup container
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt -y -qq update
          apt install -y -qq python3-pip rsync
          python3 -m pip -q install coverage
      - name: Download coverage reports from artifacts
        uses: actions/download-artifact@v3
      - name: Combine coverage reports
        run: |
          python3 -m coverage combine coverage-*/.coverage*
          python3 -m coverage report --fail-under=100 --show-missing --skip-covered

  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'viskex/viskex' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 55
