name: viskex CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - backend: dolfinx
            container: ghcr.io/fenics/dolfinx/dolfinx:nightly
            setup_container: |
              export DEBIAN_FRONTEND="noninteractive"
              apt update -y -q
              apt install -y -qq libgl1-mesa-glx xvfb
              rm /usr/local/lib/python3.10/dist-packages/petsc4py/py.typed
          - backend: firedrake
            container: firedrakeproject/firedrake
            setup_container: |
              export DEBIAN_FRONTEND="noninteractive"
              apt update -y -q
              apt install -y -qq libgl1-mesa-glx xvfb
              rm /home/firedrake/firedrake/lib/python3.10/site-packages/petsc4py/py.typed
              echo "/home/firedrake/firedrake/bin" >> $GITHUB_PATH
      fail-fast: false
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Setup container
        run: ${{ matrix.setup_container }}
      - name: Install viskex
        run: |
          BACKEND=backend_${{ matrix.backend }}
          python3 -m pip install .[${BACKEND},docs,lint,tests,tutorials]
      - name: Clean build files
        run: |
          git config --global --add safe.directory $PWD
          git clean -xdf
      - name: Update ruff configuration
        run: |
          if [[ "${{ matrix.backend }}" != "firedrake" ]]; then
            sed -i 's@from viskex.firedrake_plotter import FiredrakePlotter@# line removed by CI@g' viskex/__init__.py
            sed -i 's@firedrake = FiredrakePlotter@# line removed by CI@g' viskex/__init__.py
            sed -i 's@\[tool\.ruff\]@[tool.ruff]\nexclude = ["viskex/firedrake_plotter.py", "tests/notebooks/common_firedrake.py"]@g' pyproject.toml
          elif [[ "${{ matrix.backend }}" != "dolfinx" ]]; then
            sed -i 's@from viskex.dolfinx_plotter import DolfinxPlotter@# line removed by CI@g' viskex/__init__.py
            sed -i 's@dolfinx = DolfinxPlotter@# line removed by CI@g' viskex/__init__.py
            sed -i 's@\[tool\.ruff\]@[tool.ruff]\nexclude = ["viskex/dolfinx_plotter.py", "tests/notebooks/common_dolfinx.py"]@g' pyproject.toml
          else
            echo "Invalid backend"
            exit 1
          fi
        shell: bash
      - name: Update mypy configuration
        run: |
          if [[ "${{ matrix.backend }}" != "firedrake" ]]; then
            sed -i 's@\[tool\.mypy\]@[tool.mypy]\nexclude = "(^viskex/firedrake_plotter\\\\.py\$|^tests/notebooks/common_firedrake\\\\.py\$)"@g' pyproject.toml
          elif [[ "${{ matrix.backend }}" != "dolfinx" ]]; then
            sed -i 's@\[tool\.mypy\]@[tool.mypy]\nexclude = "(^viskex/dolfinx_plotter\\\\.py\$|^tests/notebooks/common_dolfinx\\\\.py\$)"@g' pyproject.toml
            sed -i 's@    # "dolfinx",@    "dolfinx",@g' pyproject.toml
            sed -i 's@    # "dolfinx.*",@    "dolfinx.*",@g' pyproject.toml
          else
            echo "Invalid backend"
            exit 1
          fi
        shell: bash
      - name: Run ruff on python files
        run: |
          python3 -m ruff .
      - name: Run isort on python files
        run: |
          python3 -m isort --check --diff .
      - name: Run mypy on python files
        run: |
          python3 -m mypy --exclude=conftest.py .
          python3 -m mypy tests/unit/conftest.py
          python3 -m mypy tutorials/conftest.py
      - name: Run yamllint on workflows
        run: |
          python3 -m yamllint -d "{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}" .
      - name: Run documentation generation
        run: |
          cd docs && python3 -m sphinx -W -b html . build/html
      - name: Run unit tests
        run: |
          export DISPLAY=":99"
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          COVERAGE_FILE=.coverage_unit python3 -m coverage run --source=viskex -m pytest tests/unit
      - name: Generate notebooks files
        run: |
          NO_TESTS_COLLECTED=5
          python3 -m pytest --ipynb-action=create-notebooks tests/notebooks || (($?==$NO_TESTS_COLLECTED))
          python3 -m pytest --ipynb-action=create-notebooks tutorials || (($?==$NO_TESTS_COLLECTED))
        shell: bash
      - name: Update nbqa configuration
        run: |
          if [[ "${{ matrix.backend }}" != "firedrake" ]]; then
            echo "[tool.nbqa.exclude]" >> pyproject.toml
            echo 'ruff = "(^tests/notebooks/test_.*_firedrake|^tests/notebooks/.*/test_.*_firedrake|^tutorials/.*/tutorial_.*_firedrake)"' >> pyproject.toml
            echo 'mypy = "(^tests/notebooks/test_.*_firedrake|^tests/notebooks/.*/test_.*_firedrake|^tutorials/.*/tutorial_.*_firedrake)"' >> pyproject.toml
          elif [[ "${{ matrix.backend }}" != "dolfinx" ]]; then
            echo "[tool.nbqa.exclude]" >> pyproject.toml
            echo 'ruff = "(^tests/notebooks/test_.*_dolfinx|^tests/notebooks/.*/test_.*_dolfinx|^tutorials/.*/tutorial_.*_dolfinx)"' >> pyproject.toml
            echo 'mypy = "(^tests/notebooks/test_.*_dolfinx|^tests/notebooks/.*/test_.*_dolfinx|^tutorials/.*/tutorial_.*_dolfinx)"' >> pyproject.toml
          else
            echo "Invalid backend"
            exit 1
          fi
        shell: bash
      - name: Run ruff on notebooks files
        run: |
          python3 -m nbqa ruff .
      - name: Run isort on notebooks files
        run: |
          python3 -m nbqa isort --check --diff .
      - name: Run mypy on notebooks files
        run: |
          python3 -m nbqa mypy .
      - name: Check for stray outputs, counts and metadata in ipynb files
        uses: RBniCS/check-jupyter-metadata-action@main
        with:
          pattern: "**/*.ipynb"
      - name: Run notebooks tests
        run: |
          export DISPLAY=":99"
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          for VISKEX_PYVISTA_BACKEND in "client" "html" "none" "server" "static"; do
            echo "Testing ${VISKEX_PYVISTA_BACKEND} pyvista backend"
            COVERAGE_FILE=.coverage_notebooks_${VISKEX_PYVISTA_BACKEND} VISKEX_PYVISTA_BACKEND=${VISKEX_PYVISTA_BACKEND} python3 -m pytest --cov=viskex --cov-report= tests/notebooks
          done
      - name: Run tutorials
        run: |
          export DISPLAY=":99"
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          for VISKEX_PYVISTA_BACKEND in "client" "html" "none" "server" "static"; do
            echo "Testing ${VISKEX_PYVISTA_BACKEND} pyvista backend"
            COVERAGE_FILE=.coverage_tutorials_${{ matrix.backend }} VISKEX_PYVISTA_BACKEND=${VISKEX_PYVISTA_BACKEND} python3 -m pytest --cov=viskex --cov-report= tutorials
          done
      - name: Store coverage reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.backend }}
          path: |
            .coverage_unit_${{ matrix.backend }}
            .coverage_tutorials_${{ matrix.backend }}
          retention-days: 1
      - name: Upload tutorials logs as an artifact in case of failure
        if: failure() || cancelled()
        uses: actions/upload-artifact@v3
        with:
          name: "tutorials-logs-${{ matrix.backend }}"
          path: |
            tutorials/**/.ipynb_pytest/**/*.log*

  combine_coverage:
    runs-on: ubuntu-latest
    container: ubuntu
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup container
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt update -y -q
          apt install -y -qq python3-pip rsync
          python3 -m pip -q install coverage
      - name: Download coverage reports from artifacts
        uses: actions/download-artifact@v3
      - name: Combine coverage reports (tutorials only)
        run: |
          python3 -m coverage combine coverage-*/.coverage_tutorials*
          python3 -m coverage report --fail-under=100 --show-missing --skip-covered
      - name: Combine coverage reports (notebooks tests only)
        run: |
          python3 -m coverage combine coverage-*/.coverage_notebooks*
          python3 -m coverage report --fail-under=100 --show-missing --skip-covered
      - name: Combine coverage reports (unit tests only)
        run: |
          python3 -m coverage combine coverage-*/.coverage_unit*
          python3 -m coverage report --fail-under=100 --show-missing --skip-covered

  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'viskex/viskex' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 55
